name: Deploy to Heroku

on:
  push:
    branches:
      - tasks/26-deploy-back-to-dev-env

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm install

      - name: Generate swagger schema
        run: npm run gen-schemas

      - name: Type check with TypeScript
        run: npm run tsc

      - name: Linting project
        run: npm run lint

      - name: Add mysql crtx
        run: echo "${{ env.MYSQL_SSL_CA_CERT }}" > mysql-ca.pem

      - name: Build application
        run: npm run build:dev

      - name: Prepare for Heroku
        run: rm -rf .gitignore

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "connect-api-dev"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
